import assert from "node:assert/strict";
import fs from "node:fs";

const content = fs.readFileSync(new URL("./content.js", import.meta.url), "utf8");
const bridge = fs.readFileSync(new URL("./page-bridge.js", import.meta.url), "utf8");
const background = fs.readFileSync(new URL("./background.js", import.meta.url), "utf8");
const teacherDetail = fs.readFileSync(new URL("./teacher-detail.js", import.meta.url), "utf8");
const css = fs.readFileSync(new URL("./styles.css", import.meta.url), "utf8");
const manifest = JSON.parse(fs.readFileSync(new URL("./manifest.json", import.meta.url), "utf8"));

assert.equal(content.includes("cell.appendChild"), false, "must not add children inside Vue-owned table cells");
assert.doesNotMatch(content, /zju-helper-(suggestions|selected-list)/, "course details are not duplicated in the side panel");
assert.match(content, /dataset\.zjuRowInfo/, "course overview rows receive inline information");
assert.match(content, /已选\/待筛选\/容量/, "waiting count is explicitly labelled as pending screening");
assert.match(content, /waiting \/ remaining/, "screening ratio uses waiting divided by capacity minus selected");
assert.match(content, /value < 0\.3[\s\S]*value < 1[\s\S]*value < 1\.5[\s\S]*value < 5[\s\S]*value < 10/, "screening ratio uses all requested color thresholds");
assert.match(content, /selectedRowLabel\(item, chosen\.length > 1\)/, "only multiple selected wishes show class codes");
assert.match(content, /const classPart = showClassCode \?/, "a single selected wish has no prefix or class code");
assert.doesNotMatch(content, /筛选比 \$\{ratio\(item\)\.label\}/, "displayed ratios omit the redundant label");
assert.match(content, /join\("\\n"\)/, "multiple selected wishes render on separate lines");
assert.match(content, /data-zju-switch-course/, "selected courses with alternatives expose a switch-class action");
assert.match(content, /openClassSwitchModal\(courseCode\)/, "switch-class action opens an extension-owned comparison modal");
assert.match(content, /仅查看，不会提交选退课/, "switch-class modal makes clear it does not submit enrollment actions");
assert.match(content, /classConflictState\(item, selectedIds\)/, "switch-class modal calculates conflicts against current selections");
assert.match(content, /zju-helper-switch-links/, "switch-class buttons live outside Vue-owned table cells");
assert.match(css, /#zju-helper-switch-modal/, "switch-class comparison modal has dedicated styling");
assert.match(content, /dataset\.zjuRatioLabel/, "modal enrollment cells receive a screening-ratio badge");
assert.match(css, /td\[data-zju-row-info\]::after/, "inline information is rendered without changing Vue-owned children");
assert.match(css, /td\[data-zju-ratio-label\]::after/, "modal ratio badge is rendered without changing Vue-owned children");
assert.match(content, /\.ant-modal \.ant-table-wrapper/, "class coloring is scoped to the Ant modal table");
assert.match(content, /otherCourseConflict \? "red" : sameCourseConflict \? "yellow" : "green"/, "red and yellow require real schedule conflicts");
assert.match(bridge, /name\.startsWith\("未"\)\) return false;[\s\S]*return Boolean\(item\.kcbjId\)/, "unselected status overrides a stale class id");
assert.match(bridge, /const REFRESH_INTERVAL_MS = 60 \* 1000/, "automatic refresh interval is one minute");
assert.match(bridge, /item\.sksjdd \|\| item\.sksjdds \|\| item\.sjdd \|\| course\.schedule/, "class normalization falls back to all known schedule fields");
assert.match(bridge, /工程师学院/, "engineering campus is recognized in page data");
assert.match(bridge, /lastRefreshAt && Date\.now\(\) < cooldownUntil/, "manual refreshes share a cooldown window");
assert.match(content, /冷却中/, "refresh button shows a cooldown state");
assert.match(content, /load-teachers/, "teacher ratings are loaded through the extension worker");
assert.match(content, /常住校区提醒（可多选）/, "campus warning settings are present in the side panel");
assert.match(content, /工程师学院/, "engineering campus is available in campus settings");
assert.match(content, /const byCourseId = new Map\(\)/, "campus warnings resolve selected classes by course id when class ids are stale");
assert.doesNotMatch(content, /warning\.innerHTML/, "campus warning values are not injected as HTML");
assert.match(content, /data-zju-teacher-info/, "teacher ratings are marked next to teacher names");
assert.doesNotMatch(content, /查老师评分：/, "teacher annotations do not display the redundant 查老师 label");
assert.match(content, /searchParams\.set\("teacherId", item\.id\)/, "teacher ratings link to a teacher-specific detail URL");
assert.match(content, /zju-helper-teacher-links/, "teacher score links render in an extension-owned overlay layer");
assert.match(content, /link\.target = "_blank"/, "teacher detail links open in a new tab");
assert.doesNotMatch(content, /stopPropagation\(\)/, "teacher score links do not interrupt Vue click handlers");
assert.doesNotMatch(content, /bindTeacherNavigation/, "teacher links do not depend on fragile click interception");
assert.match(content, /scheduleTeacherDecorate\(\);[\s\S]*setTimeout\(loadTeacherRatings, 0\)/, "course rendering precedes teacher loading");
assert.match(teacherDetail, /input\.dispatchEvent\(new Event\("input", \{ bubbles: true \}\)\)/, "teacher detail page searches for the requested teacher");
assert.match(teacherDetail, /link\.click\(\)/, "teacher detail page opens the matching details link");
assert.match(background, /teachers\.csv/, "teacher data source is the public chalaoshi CSV");
assert.equal(manifest.background?.service_worker, "background.js");
assert.ok(manifest.host_permissions.includes("https://chalaoshi.netlify.app/*"));
assert.ok(manifest.content_scripts.some(script => script.js?.includes("teacher-detail.js")), "teacher detail helper runs on chalaoshi");
assert.match(content, /"textContent" in value/, "DOM elements are read through textContent");
assert.match(content, /#zju-helper-panel, #zju-helper-teacher-links/, "extension-owned layers do not trigger an observer loop");
assert.match(content, /element\.closest\?\.\("table, \.ant-modal, \.ant-table-wrapper"\)/, "mutation observer ignores unrelated page updates");
assert.match(content, /const teachersByName = new Map\(\)/, "teacher decoration uses a name index instead of scanning all ratings per cell");
assert.doesNotMatch(css, /box-shadow: inset 4px/, "ratio text has no left-side color bar");
assert.doesNotMatch(css, /--zju-ratio-bg/, "ratio colors do not add a background");
assert.match(content, /zju-helper-collapse/, "side panel has a collapse control");
assert.match(css, /data-collapsed="true"/, "collapsed side panel stays as a bottom bar");
assert.match(css, /#zju-helper-teacher-links/, "teacher score hitboxes live outside Vue-owned tables");
assert.equal(manifest.version, "0.6.5");

console.log("regression checks passed");
